model:
  base: model/Base
  adapter:
    path: model/Tina/checkpoint-2000
data:
  dataset_name: jsonl   # 'jsonl' or 'glaive'
  jsonl: data/train.jsonl
  split: train
  path: null
  streaming: false
  val_split: null
  limit_train: null
  batch_size: 8
  strict: true
schedule:
  steps: 10000
  sample_every: 50
  budget_cap: 128
lambdas:
  answer_ce: 1.0
  gate_reg: 0.0001
  plan_ce: 0.5
  budget_reg: 0.1
  conf_cal: 0.1
  rewrite: 0.2
  style_inv: 0.2
taps: [6, 10, 14]
logging:
  eval_every: 500
  out_dir: artifacts

sample_every: 50
budget_cap: 128
losses:
  lambda_rewrite: 0.1
metacog:
  linked_all_layers: true
  proj_dim: 128
  agg: attn
  head_temp: 1.0
  var_reg: 0.0
conditioning:
  film: true
  film_scale: 0.05
  per_layer: true
optim:
  heads_lr: 5.0e-4
  adapters_lr: 2.0e-4
  base_top_lr: 5.0e-5
  wd: 0.01
  clip: 1.0
fp:
  dtype: bf16
  grad_ckpt: true
trainer:
  enabled: false
  epochs: 3
  steps_per_eval: 1000
  on_policy_interval: 200
  mode: supervised  # supervised | self_play | hybrid
  hybrid_schedule:
    supervised_steps: 1000
    self_play_iters: 200
self_play:
  buffer_size: 4096
  num_propose: 16
  num_mc_rollouts: 4
  lambda_learnability: 1.0
  lambda_solver: 1.0
  lambda_format: 0.1
  task_types: [deduction, abduction, induction]
  max_program_len: 128
  introspection_coeff: 0.1  # weight to boost learnability based on metacog signals
phases:
  - {name: A, freeze_base: true,  train_adapters: true,  train_heads: true,  train_base_top: false, use_on_policy: false, budget_penalty_w: 0.0, think_ce_w: 0.0, quiet_star_w: 0.0}
  - {name: B, freeze_base: true,  train_adapters: true,  train_heads: true,  train_base_top: false, use_on_policy: true,  budget_penalty_w: 0.1, think_ce_w: 0.0, quiet_star_w: 0.05}
  - {name: C, freeze_base: false, train_adapters: true,  train_heads: true,  train_base_top: true,  use_on_policy: true,  budget_penalty_w: 0.2, think_ce_w: 0.1, quiet_star_w: 0.1}
  - {name: D, freeze_base: true,  train_adapters: true,  train_heads: true,  train_base_top: false, use_on_policy: true,  budget_penalty_w: 0.1, think_ce_w: 0.0, quiet_star_w: 0.05}
