model:
  base: model/Base
  adapter:
    path: model/Tina/checkpoint-2000
data:
  jsonl: data/train.jsonl
  batch_size: 8
  strict: true
schedule:
  steps: 10000
  sample_every: 50
  budget_cap: 128
lambdas:
  answer_ce: 1.0
  gate_reg: 0.0001
  plan_ce: 0.5
  budget_reg: 0.1
  conf_cal: 0.1
  rewrite: 0.2
  style_inv: 0.2
taps: [6, 10, 14]
logging:
  eval_every: 500
  out_dir: artifacts

sample_every: 50
budget_cap: 128
metacog:
  linked_all_layers: true
  proj_dim: 128
  agg: attn
  head_temp: 1.0
  var_reg: 0.0
conditioning:
  film: true
  film_scale: 0.05
  per_layer: true
