data_mixture:
  datasets:
    - name: gsm8k
      adapter: gsm8k_adapter
      weight: 1.0
    - name: math
      adapter: math_adapter
      weight: 0.7
    - name: mbpp
      adapter: mbpp_adapter
      weight: 0.6
    - name: logic
      adapter: logic_adapter
      weight: 0.8
  temperature_sampling: 0.7
  probe_first_n: 10000
  target_depth_mix: {short: 0.35, mid: 0.45, long: 0.20}

losses:
  lambda_over: 0.2
  lambda_under: 0.5
  expert_entropy_reg: 0.01

bins:
  short: [0, 64]
  mid: [65, 256]
  long: [257, 512]
