name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          # Fallback if optional extras not resolved
          pip install --upgrade pytest jsonschema ruff mypy || true
      - name: Validate configs
        run: |
          python tools/validate_configs.py --all --train-config train_config.yaml || python tools/validate_configs.py
      - name: Run tests
        run: pytest -q
