name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pytest fastapi httpx transformers tokenizers
      - name: Lint (ruff)
        run: |
          ruff check .
          ruff format --check .
      - name: Type check (mypy)
        run: mypy .
      - name: Security (bandit)
        run: bandit -c bandit.yaml -r .
      - name: Tests (pytest)
        run: pytest -q
