name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Minimal test deps
          pip install pytest transformers torch --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Run tests
        env:
          HF_HUB_OFFLINE: "1"
          HF_HUB_DISABLE_TELEMETRY: "1"
          TOKENIZER_PARALLELISM: "false"
          CUDA_VISIBLE_DEVICES: ""
        run: |
          pytest -q
